//it uses req.user.id generated by middleware
//it tryes to get user info from database from the Id it got from req =>  const user=await Usermodel.findById(req.user.id)
//after finding complete user info it send it in a res

const Usermodel=require("../../models/userModel")
module.exports.userDetails=async(req,res,err)=>{
    try {
        const user=await Usermodel.findById(req.user.id)
        
        res.status(200).json({
            message : "User details fetched successfully",
            data : user,
            error : false,
            success : true
        })
    } catch (error) {
        message=error.message
        res.status(400).json({
            message : message || error,
            error : true,
            success : false,
        })
    }
}